name: openchat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  dio: ^4.0.4
  image_picker: ^0.8.4+10
  easy_localization: ^3.0.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  skeletons: ^0.0.3
  google_fonts: 2.1.1
  fluttertoast: 8.0.8
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/icon/icon.png"

flutter_native_splash:
  color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/localization/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700